---

kind: pipeline
name: ansible-ci

workspace:
  base: /drone
  path: src/${DRONE_REPO}

steps:
  - name: galaxy
    image: lowess/drone-molecule:2.6.8
    environment:
      GALAXY_TOKEN:
        from_secret: ansible_galaxy_token
    commands:
      - ansible-galaxy login --github-token $GALAXY_TOKEN
      - ansible-galaxy import \
          $DRONE_REPO_NAMESPACE $DRONE_REPO_NAME
